'use client';
import {useEffect,useRef,useState} from 'react';
const tabs=['Inicio','Eventos','Plantillas','Música','Modo 360'];
export default function Home(){const [tab,setTab]=useState('Inicio');const [events,setEvents]=useState([]);const [templates,setTemplates]=useState([]);const [music,setMusic]=useState([]);const [count,setCount]=useState(null);const [recording,setRecording]=useState(false);const video=useRef(null);const recorder=useRef(null);const chunks=useRef([]);
useEffect(()=>{setEvents(JSON.parse(localStorage.getItem('b360-events')||'[]'));},[]);
const addEvent=()=>{const name=prompt('Nombre del evento');if(!name)return;const n=[...events,{name,date:new Date().toLocaleDateString('es-CL')}];setEvents(n);localStorage.setItem('b360-events',JSON.stringify(n));};
const files=(e,setter)=>setter(x=>[...x,...Array.from(e.target.files).map(f=>({name:f.name,url:URL.createObjectURL(f)}))]);
async function camera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:true});video.current.srcObject=s;}catch(e){alert('Debes permitir acceso a cámara y micrófono.');}}
async function start(){if(!video.current?.srcObject)await camera();let n=3;setCount(n);const t=setInterval(()=>{n--;if(n===0){clearInterval(t);setCount(null);const s=video.current.srcObject;chunks.current=[];recorder.current=new MediaRecorder(s);recorder.current.ondataavailable=e=>chunks.current.push(e.data);recorder.current.onstop=()=>{const blob=new Blob(chunks.current,{type:'video/webm'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bursan360-${Date.now()}.webm`;a.click();};recorder.current.start();setRecording(true);}else setCount(n)},1000)}
function stop(){recorder.current?.stop();setRecording(false)}
return <main><header><div className="brand"><span>360°</span><div><b>BURSAN 360</b><small>Experiencias para eventos</small></div></div><button className="primary" onClick={()=>setTab('Modo 360')}>Iniciar 360</button></header><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section>
{tab==='Inicio'&&<><div className="hero"><p>PLATAFORMA 360</p><h1>Crea, graba y comparte<br/>momentos increíbles.</h1><span>Configura tu evento, carga tus propios diseños y música, y graba directamente desde el teléfono.</span><button className="primary big" onClick={()=>setTab('Modo 360')}>Abrir cámara 360</button></div><div className="grid"><Card title="Eventos" text={`${events.length} eventos creados`} action={()=>setTab('Eventos')}/><Card title="Plantillas" text="Sube overlays PNG y diseños" action={()=>setTab('Plantillas')}/><Card title="Música" text="Tu biblioteca de sonidos" action={()=>setTab('Música')}/></div></>}
{tab==='Eventos'&&<Panel title="Eventos" subtitle="Organiza cada celebración con su propia configuración."><button className="primary" onClick={addEvent}>+ Crear evento</button><div className="items">{events.length?events.map((e,i)=><article key={i}><b>{e.name}</b><small>{e.date}</small></article>):<Empty text="Aún no has creado eventos."/>}</div></Panel>}
{tab==='Plantillas'&&<Panel title="Plantillas" subtitle="Sube marcos y overlays transparentes para tus videos."><label className="upload">+ Subir plantilla PNG<input hidden type="file" accept="image/png,image/webp" multiple onChange={e=>files(e,setTemplates)}/></label><div className="items thumbs">{templates.map((x,i)=><article key={i}><img src={x.url}/><b>{x.name}</b></article>)}{!templates.length&&<Empty text="Tus plantillas aparecerán aquí."/>}</div></Panel>}
{tab==='Música'&&<Panel title="Música y sonidos" subtitle="Carga canciones o efectos para utilizarlos en tus eventos."><label className="upload">+ Subir audio<input hidden type="file" accept="audio/*" multiple onChange={e=>files(e,setMusic)}/></label><div className="items">{music.map((x,i)=><article key={i}><b>{x.name}</b><audio controls src={x.url}/></article>)}{!music.length&&<Empty text="Tu biblioteca de audio está vacía."/>}</div></Panel>}
{tab==='Modo 360'&&<Panel title="Modo 360" subtitle="Coloca el teléfono en el brazo de la plataforma y comienza la experiencia."><div className="camera"><video ref={video} autoPlay muted playsInline/>{count&&<div className="count">{count}</div>}{!video.current?.srcObject&&<button onClick={camera}>Activar cámara</button>}</div><div className="controls">{!recording?<button className="record" onClick={start}>● Grabar</button>:<button className="stop" onClick={stop}>■ Finalizar y guardar</button>}</div><p className="note">El video se procesa en el dispositivo y se descarga localmente. No se sube a Supabase.</p></Panel>}
</section></main>}
function Card({title,text,action}){return <article className="card" onClick={action}><div className="icon">✦</div><h3>{title}</h3><p>{text}</p><b>Abrir →</b></article>};function Panel({title,subtitle,children}){return <div className="panel"><div><p className="eyebrow">BURSAN 360</p><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>};function Empty({text}){return <div className="empty">{text}</div>}
