'use client';
import {useEffect,useRef,useState} from 'react';
const tabs=['Inicio','Eventos','Plantillas','Música','Modo 360'];
export default function Home(){
 const [tab,setTab]=useState('Inicio'),[events,setEvents]=useState([]),[templates,setTemplates]=useState([]),[music,setMusic]=useState([]),[selectedTemplate,setSelectedTemplate]=useState(null),[selectedMusic,setSelectedMusic]=useState(null),[count,setCount]=useState(null),[recording,setRecording]=useState(false),[notice,setNotice]=useState(''),[lastVideo,setLastVideo]=useState(null),[cameraOn,setCameraOn]=useState(false),[cameraError,setCameraError]=useState('');
 const video=useRef(null),recorder=useRef(null),chunks=useRef([]),canvas=useRef(null),animation=useRef(null);
 useEffect(()=>{setEvents(JSON.parse(localStorage.getItem('b360-events')||'[]'));return()=>{const s=video.current?.srcObject;s?.getTracks?.().forEach(t=>t.stop())}},[]);
 const flash=m=>{setNotice(m);setTimeout(()=>setNotice(''),3000)};
 const addEvent=()=>{const name=prompt('Nombre del evento');if(!name)return;const n=[...events,{name,date:new Date().toLocaleDateString('es-CL')}];setEvents(n);localStorage.setItem('b360-events',JSON.stringify(n));flash('Evento creado correctamente');};
 const uploadTemplates=e=>{const fs=Array.from(e.target.files);if(!fs.length)return;const added=fs.map(f=>({name:f.name,url:URL.createObjectURL(f)}));setTemplates(x=>[...x,...added]);if(!selectedTemplate)setSelectedTemplate(added[0]);flash(`${fs.length} plantilla${fs.length>1?'s':''} cargada${fs.length>1?'s':''} correctamente`);e.target.value='';};
 const uploadMusic=e=>{const fs=Array.from(e.target.files);if(!fs.length)return;const added=fs.map(f=>({name:f.name,url:URL.createObjectURL(f)}));setMusic(x=>[...x,...added]);if(!selectedMusic)setSelectedMusic(added[0]);flash(`${fs.length} audio${fs.length>1?'s':''} cargado${fs.length>1?'s':''}`);e.target.value='';};
 async function camera(){setCameraError('');if(!window.isSecureContext){setCameraError('La cámara requiere una conexión HTTPS segura.');return null}if(!navigator.mediaDevices?.getUserMedia){setCameraError('Este navegador no permite acceso a la cámara. Abre Bursan 360 directamente en Safari.');return null}try{video.current?.srcObject?.getTracks?.().forEach(t=>t.stop());let s;try{s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:true})}catch(e){if(e?.name==='NotAllowedError')throw e;s=await navigator.mediaDevices.getUserMedia({video:true,audio:true})}if(!video.current)return null;video.current.srcObject=s;video.current.muted=true;video.current.setAttribute('playsinline','true');await video.current.play();setCameraOn(true);flash(s.getAudioTracks().length?'Cámara y micrófono activados':'Cámara activada, pero no hay micrófono');return s}catch(e){console.error('Bursan360 media error',e);const msg=e?.name==='NotAllowedError'?'Permiso de cámara o micrófono bloqueado. En iPhone permite Cámara y Micrófono para este sitio en Safari.':e?.name==='NotFoundError'?'No se encontró cámara o micrófono disponible.':e?.name==='NotReadableError'?'La cámara o el micrófono están siendo utilizados por otra aplicación.':`No fue posible activar cámara/micrófono (${e?.name||'error'}).`;setCameraError(msg);setCameraOn(false);return null}}
 function bestMime(){const opts=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];return opts.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||''}
 async function buildStream(){const source=video.current?.srcObject||await camera();if(!source)return null;const c=canvas.current,ctx=c?.getContext?.('2d');if(!c||!ctx)return source;c.width=1080;c.height=1920;let overlay=null;if(selectedTemplate){overlay=new Image();overlay.src=selectedTemplate.url;try{await overlay.decode()}catch{}}
 const draw=()=>{if(!video.current)return;ctx.clearRect(0,0,c.width,c.height);const v=video.current,vw=v.videoWidth||1080,vh=v.videoHeight||1920,scale=Math.max(c.width/vw,c.height/vh),w=vw*scale,h=vh*scale;ctx.drawImage(v,(c.width-w)/2,(c.height-h)/2,w,h);if(overlay)ctx.drawImage(overlay,0,0,c.width,c.height);animation.current=requestAnimationFrame(draw)};draw();if(typeof c.captureStream!=='function')return source;const output=c.captureStream(30);source.getAudioTracks().forEach(track=>output.addTrack(track));return output}
 async function beginRecording(){if(!window.MediaRecorder){setCameraError('Este navegador no admite grabación web. Prueba abriendo la página directamente en Safari actualizado.');return}const s=await buildStream();if(!s)return;if(!s.getAudioTracks().length){setCameraError('El micrófono no está disponible. Revisa el permiso de Micrófono en Safari antes de grabar.');return}const mime=bestMime();chunks.current=[];try{recorder.current=new MediaRecorder(s,mime?{mimeType:mime,videoBitsPerSecond:10000000,audioBitsPerSecond:128000}:undefined)}catch{recorder.current=new MediaRecorder(s)}recorder.current.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};recorder.current.onstop=()=>{cancelAnimationFrame(animation.current);const type=recorder.current.mimeType||mime||'video/mp4',blob=new Blob(chunks.current,{type}),ext=type.includes('mp4')?'mp4':'webm',file=new File([blob],`bursan360-${Date.now()}.${ext}`,{type}),url=URL.createObjectURL(blob);setLastVideo({url,file,ext});flash(`Video ${ext.toUpperCase()} con audio listo`)};recorder.current.start(250);setRecording(true)}
 async function start(){if(!cameraOn){const s=await camera();if(!s)return}let n=3;setCount(n);const t=setInterval(()=>{n--;if(n===0){clearInterval(t);setCount(null);beginRecording()}else setCount(n)},1000)}
 function stop(){recorder.current?.stop();setRecording(false)}
 async function shareVideo(){if(!lastVideo)return;if(navigator.canShare?.({files:[lastVideo.file]})){try{await navigator.share({files:[lastVideo.file],title:'Bursan 360'});return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=lastVideo.url;a.download=lastVideo.file.name;a.click()}
 return <main>{notice&&<div className="toast">✓ {notice}</div>}<header><div className="brand"><span>360°</span><div><b>BURSAN 360</b><small>Experiencias para eventos</small></div></div><button className="primary" onClick={()=>setTab('Modo 360')}>Iniciar 360</button></header><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section>
 {tab==='Inicio'&&<><div className="hero"><p>PLATAFORMA 360</p><h1>Crea, graba y comparte<br/>momentos increíbles.</h1><span>Configura tu evento, carga tus propios diseños y música, y graba directamente desde el teléfono.</span><button className="primary big" onClick={()=>setTab('Modo 360')}>Abrir cámara 360</button></div><div className="grid"><Card title="Eventos" text={`${events.length} eventos creados`} action={()=>setTab('Eventos')}/><Card title="Plantillas" text={`${templates.length} plantillas cargadas`} action={()=>setTab('Plantillas')}/><Card title="Música" text={`${music.length} audios cargados`} action={()=>setTab('Música')}/></div></>}
 {tab==='Eventos'&&<Panel title="Eventos" subtitle="Organiza cada celebración con su propia configuración."><button className="primary" onClick={addEvent}>+ Crear evento</button><div className="items">{events.length?events.map((e,i)=><article key={i}><b>{e.name}</b><small>{e.date}</small></article>):<Empty text="Aún no has creado eventos."/>}</div></Panel>}
 {tab==='Plantillas'&&<Panel title="Plantillas" subtitle="La plantilla seleccionada se verá sobre la cámara y quedará integrada en la grabación."><label className="upload">+ Subir plantilla PNG<input hidden type="file" accept="image/png,image/webp" multiple onChange={uploadTemplates}/></label><p className="status">{templates.length?`✓ ${templates.length} plantilla${templates.length>1?'s':''} cargada${templates.length>1?'s':''}. Toca una para seleccionarla.`:'Aún no hay plantillas cargadas.'}</p><div className="items thumbs">{templates.map((x,i)=><article className={selectedTemplate?.url===x.url?'selected':''} onClick={()=>{setSelectedTemplate(x);flash(`Plantilla “${x.name}” seleccionada`)}} key={i}><img src={x.url}/><b>{x.name}</b><small>{selectedTemplate?.url===x.url?'✓ Activa':'Tocar para usar'}</small></article>)}</div></Panel>}
 {tab==='Música'&&<Panel title="Música y sonidos" subtitle="Carga canciones o efectos para tus eventos."><label className="upload">+ Subir audio<input hidden type="file" accept="audio/*" multiple onChange={uploadMusic}/></label><div className="items">{music.map((x,i)=><article className={selectedMusic?.url===x.url?'selected':''} onClick={()=>setSelectedMusic(x)} key={i}><b>{x.name}</b><audio controls src={x.url}/><small>{selectedMusic?.url===x.url?'✓ Seleccionado':'Tocar para seleccionar'}</small></article>)}{!music.length&&<Empty text="Tu biblioteca de audio está vacía."/>}</div></Panel>}
 {tab==='Modo 360'&&<Panel title="Modo 360" subtitle="Activa cámara y micrófono. La plantilla activa aparecerá sobre la imagen."><div className="modebar"><span>Plantilla: <b>{selectedTemplate?.name||'Sin plantilla'}</b></span><button onClick={()=>setTab('Plantillas')}>Cambiar</button></div>{cameraError&&<div className="cameraError">⚠ {cameraError}</div>}<div className="camera"><video ref={video} autoPlay muted playsInline/>{selectedTemplate&&<img className="liveOverlay" src={selectedTemplate.url}/>}<canvas ref={canvas} className="hiddenCanvas"/>{count&&<div className="count">{count}</div>}{!cameraOn&&<button className="cameraStart" onClick={camera}>📷 Activar cámara + micrófono</button>}</div><div className="controls">{cameraOn&&!recording&&<button className="record" onClick={start}>● Grabar con audio</button>}{recording&&<button className="stop" onClick={stop}>■ Finalizar</button>}</div>{lastVideo&&<div className="result"><video controls playsInline src={lastVideo.url}/><div><b>Video listo ({lastVideo.ext.toUpperCase()})</b><button className="primary" onClick={shareVideo}>Guardar / Compartir</button></div></div>}<p className="note">La vista previa está silenciada para evitar eco, pero el archivo final incluye el audio capturado por el micrófono.</p></Panel>}
 </section></main>}
function Card({title,text,action}){return <article className="card" onClick={action}><div className="icon">✦</div><h3>{title}</h3><p>{text}</p><b>Abrir →</b></article>};function Panel({title,subtitle,children}){return <div className="panel"><div><p className="eyebrow">BURSAN 360</p><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>};function Empty({text}){return <div className="empty">{text}</div>}
